export * from './agenda-controller.controller';
export * from './agenda-pacientes.controller';
export * from './expediente-controller.controller';
export * from './expedientes-pacientes.controller';
export * from './paciente-controller.controller';
export * from './pacientes-psicologos.controller';
export * from './ping.controller';
export * from './psicologo-controller.controller';
export * from './login-controller.controller';
